DUPLO-25704: Wait on bulk update image
duplocloud/duploctl pull request #110
Opened 2024-10-25 20:18 UTC by shantanuduplo

2024-10-25 20:19 UTC, zafarabbas commented
Task linked: [DUPLO-25704 Wait on bulk update image](https://app.clickup.com/t/8655600/DUPLO-25704)

2024-10-25 21:51 UTC, kferrone requested changes

2024-10-25 21:51 UTC, kferrone commented on src/duplo_resource/service.py
> -    Usage: Basic CLI Use
Don't remove the basica usage part. Add that back in this pr

2024-10-28 16:56 UTC, kferrone approved these changes

2024-10-28 16:57 UTC, merged