DUPLO-15739: Added Tenant DNS Config command
duplocloud/duploctl pull request #92
Opened 2024-08-05 22:31 UTC by shantanuduplo

2024-08-05 22:31 UTC, zafarabbas commented
Task linked: [DUPLO-15739 Tenant DNS Config Endpoint](https://app.clickup.com/t/8655600/DUPLO-15739)

2024-08-06 19:57 UTC, kferrone requested changes

2024-08-06 19:57 UTC, kferrone commented on src/duplo_resource/tenant.py
> +    return {
simply respond with the body, no need to make an extra wrapper
```python
return response.json()
```

2024-08-08 14:00 UTC, kferrone requested changes

2024-08-08 14:00 UTC, kferrone commented on src/duplo_resource/tenant.py
> +    response.json()
where is the `return`?

2024-08-08 17:07 UTC, kferrone approved these changes

2024-08-08 17:08 UTC, merged